---
title: "¡Hola!"
---

My name is Francisco Ramírez, but everybody calls me Paco. 

I'm currently a Master's in Data Science student at The University of British Columbia in Vancouver, BC.

I graduated as a Mechanical Engineer from ITESM in Mexico, which was followed by a Masters from UCL in the UK. 

I have a background in Mechanical Engineering and over 10 years of experience in the aerospace industry working for GE Aerospace focusing on aircraft and gas turbine engine performance, most recently in technical leadership and management roles.

I am looking forward to joining the Data Science community in Vancouver, BC!

Thank you for visiting my website!

You can send me an email through the form below, or at [fraramfra@gmail.com](mailto:fraramfra@gmail.com), or feel free to contact me through [LinkedIn](https://www.linkedin.com/in/fraramfra/).

<form
  action="https://formspree.io/f/meoaaelp"
  method="POST"
>
  <label>
    Your email:
    <input type="email" name="email">
  <label>
  <label>
    Your message:
    <textarea name="message"></textarea>
  </label>
  <button type="submit">Send</button>
</form>


